// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVhHc_PG-oIhLDYt1hFHZFQABpgJaauqQ',
    appId: '1:682262065752:web:fdcb308a63fae57288502d',
    messagingSenderId: '682262065752',
    projectId: 'solemarket-licenta',
    authDomain: 'solemarket-licenta.firebaseapp.com',
    storageBucket: 'solemarket-licenta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqDHJoWqcVH05NEY3bCp7e-K7jvGAaNZY',
    appId: '1:682262065752:android:23a3e24b44311b2e88502d',
    messagingSenderId: '682262065752',
    projectId: 'solemarket-licenta',
    storageBucket: 'solemarket-licenta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_VLwfCgZFGQNN93PFWa_vZuc69G6pMKo',
    appId: '1:682262065752:ios:c2a308d5aaf530c288502d',
    messagingSenderId: '682262065752',
    projectId: 'solemarket-licenta',
    storageBucket: 'solemarket-licenta.appspot.com',
    iosBundleId: 'com.example.soleMarketProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_VLwfCgZFGQNN93PFWa_vZuc69G6pMKo',
    appId: '1:682262065752:ios:15d49991c6c85fff88502d',
    messagingSenderId: '682262065752',
    projectId: 'solemarket-licenta',
    storageBucket: 'solemarket-licenta.appspot.com',
    iosBundleId: 'com.example.soleMarketProject.RunnerTests',
  );
}
